[build]
publish = "out/"
command = "npm run build"

[dev]
command = "npm run watch"

[context.dev.environment]
NODE_VERSION = "20.6.1"

[context.deploy-preview.environment]
NODE_VERSION = "20.6.1"

[context.production.environment]
NODE_VERSION = "20.6.1"
NODE_ENV = "production"

[[edge_functions]]
path = "/.well-known/webfinger"
function = "webfinger-redirect"

[[headers]]
for = "/public.pgp"

[headers.values]
Content-Type = "application/pgp-keys"

[[redirects]]
from = "/license"
to = "/license.txt"

[[redirects]]
from = "/LICENSE"
to = "/license.txt"

[[redirects]]
from = "/commit"
to = "/commit.txt"

[[redirects]]
from = "/COMMIT"
to = "/commit.txt"

[[redirects]]
from = "/blog"
to = "/blog/toc/1"

[[redirects]]
from = "/blog/toc"
to = "/blog/toc/1"

[[redirects]]
from = "/blog/categories/:category"
to = "/blog/categories/:category/1"

[[redirects]]
from = "/gallery"
to = "/gallery/1"

[[redirects]]
from = "/blog/posts/2023-05-28-12-00-00-blocking-hacker-news"
to = "/blog/posts/2023-05-28-blocking-hacker-news"

[[redirects]]
from = "/media/*"
to = "https://f005.backblazeb2.com/file/phoebecodes-personal-site-assets/:splat"
status = 200
