[build]
	publish = "out/"
	command = "npm run build"

[dev]
	command = "npm run watch"

[[edge_functions]]
	path = "/*"
	function = "block-hacker-news"

[[headers]]
	for = "/public.pgp"

	[headers.values]
		Content-Type = "application/pgp-keys"

[[redirects]]
	from = "/license"
	to = "/license.txt"

[[redirects]]
	from = "/LICENSE"
	to = "/license.txt"

[[redirects]]
	from = "/LICENSE.txt"
	to = "/license.txt"

[[redirects]]
	from = "/commit"
	to = "/commit.txt"

[[redirects]]
	from = "/COMMIT"
	to = "/commit.txt"

[[redirects]]
	from = "/COMMIT.txt"
	to = "/commit.txt"

[[redirects]]
	from = "/blog"
	to = "/blog/toc/1"

[[redirects]]
	from = "/blog/toc"
	to = "/blog/toc/1"

[[redirects]]
	from = "/blog/tags/:tag"
	to = "/blog/tags/:tag/1"
